typing: Add a type hint for the converters in `OperationColumnFilter._convert_value_for_column`.
The next commit will introduce datetime/date methods as callables to convert values. Without this type hint, mypy will complain:

> sqladmin/filters.py:312: error: "object" not callable  [operator]